feeddeck/feeddeck

supabase/functions/_shared/feed/podcast.ts
This commit improves the parsing of the RSS feeds for a podcast, because some podcasts were not working as expected:
- The "https://gotime.fm/rss" podcast uses the "itunes:image" field for the podcast icon instead of "image", so that we now looking at both fields to add the podcast icon.
- The "https://itsallwidgets.com/podcast/feed" podcast didn't contain a link in the entries, so that all entries were skipped. For that a podcast must not contain a link anymore to be parsed, but most contain a media file which can be played within the app.
=> [podcast] Improve Parsing

app/lib/repositories/items_repository.dart
When a user scrolls through a list of items and loads more items via the "Load More" button and then clicks on the mark all items as read button, it could happen that the request fails, because Supabase can not handle the update filter with a large list of item ids.
To avoid this error we are splitting the list of item ids provided in the "updateReadStates" into chunks of 25 items for the in clause in the update filter.
=> [core] Fix Update of Read State for Large List of Items

.github/workflows/continuous-delivery.yaml, CONTRIBUTING.md, app/android/build.gradle, app/ios/Podfile, app/ios/Podfile.lock, app/ios/Runner.xcodeproj/project.pbxproj, app/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, app/lib/models/profile.dart, app/lib/repositories/app_repository.dart, app/lib/repositories/profile_repository.dart, app/lib/widgets/column/header/column_layout_header_settings.dart, app/lib/widgets/column/header/column_layout_header_settings_delete_column.dart, app/lib/widgets/item/details/item_details_mastodon.dart, app/lib/widgets/item/details/utils/item_media_gallery.dart, app/lib/widgets/item/preview/utils/item_media_gallery.dart, app/lib/widgets/settings/premium/settings_premium.dart, app/lib/widgets/settings/profile/settings_profile.dart, app/lib/widgets/settings/profile/settings_profile_open_web_app.dart, app/lib/widgets/settings/settings.dart, app/lib/widgets/source/source_list_item.dart, app/macos/Podfile, app/macos/Podfile.lock, app/macos/Runner.xcodeproj/project.pbxproj, app/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, app/pubspec.lock, app/pubspec.yaml
Update the used Flutter version to 3.13.7 and update all Flutter packages to their latest version.
=> [core] Update Flutter to v3.13.7

landing/package-lock.json, landing/package.json, supabase/email-templates/package-lock.json, supabase/email-templates/package.json
Update the npm packages used by the email templates and the landing page.
=> [core] Update NPM Packages

.github/dependabot.yml
Add a configuration for Dependabot to keep our dependencies up to date.
=> [core] Add Dependabot Configuration

app/lib/widgets/settings/premium/settings_premium.dart, app/lib/widgets/settings/premium/settings_premium_inapp.dart, app/lib/widgets/settings/premium/settings_premium_inapp_restore.dart
This commit enables in-app purchases for Android, so that a user can also subscribe to FeedDeck Premium on Android.
=> [core] Enable In-App Purchases for Android

.github/workflows/continuous-delivery.yaml, app/linux/flutter/generated_plugin_registrant.cc, app/linux/flutter/generated_plugins.cmake, app/pubspec.lock, app/pubspec.yaml, app/windows/flutter/generated_plugin_registrant.cc, app/windows/flutter/generated_plugins.cmake
Instead of using the "just_audio_windows" and "just_audio_mpv" packages for Windows and Linux, we are now using "just_audio_media_kit", so that the audio player is working reliable on these platforms.
Note: We have to adjust the Flatpak, to include the dependencies which are required on Linux.
=> [podcast] Fix Audio Player for Windows and Linux

app/lib/widgets/settings/profile/settings_profile_signout.dart
Until now a user was always signed out from all devices when he clicked on the "Sign Out" button in the settings. Now we will display a actions modal bottom sheet where a user can select if he wants to sign out from the current device or from all devices.
For this we pass the [SignOutScope] to the "signOut" function of Supabase. if the scope is "local" the user will be signed out from the current device. If the scope is "global" the user will be signed out from all devices.
=> [core] Sign Out from Current Device

supabase/functions/add-source-v1/index.ts, supabase/functions/delete-user-v1/index.ts, supabase/functions/generate-magic-link-v1/index.ts, supabase/functions/image-proxy-v1/index.ts, supabase/functions/profile-v1/index.ts, supabase/functions/profile-v2/github.ts, supabase/functions/profile-v2/index.ts, supabase/functions/stripe-create-billing-portal-link-v1/index.ts, supabase/functions/stripe-create-checkout-session-v1/index.ts
We have to add the "charset" parameter to the "Content-Type" header when we return json from one of the Supabase functions, so that special characters are properly decoded in Flutter.
=> [core] Fix Decoding of Special Characters

supabase/functions/_shared/feed/medium.ts
=> [medium] Extend Filter Words List

supabase/functions/_shared/feed/github.ts, supabase/functions/_shared/feed/googlenews.ts, supabase/functions/_shared/feed/lemmy.ts, supabase/functions/_shared/feed/mastodon.ts, supabase/functions/_shared/feed/medium.ts, supabase/functions/_shared/feed/nitter.ts, supabase/functions/_shared/feed/pinterest.ts, supabase/functions/_shared/feed/podcast.ts, supabase/functions/_shared/feed/reddit.ts, supabase/functions/_shared/feed/rss.ts, supabase/functions/_shared/feed/stackoverflow.ts, supabase/functions/_shared/feed/tumblr.ts, supabase/functions/_shared/feed/x.ts, supabase/functions/_shared/feed/youtube.ts, supabase/functions/_shared/utils/encrypt.ts, supabase/functions/_shared/utils/index.ts, supabase/functions/_shared/utils/md5.ts, supabase/functions/import_map.json
This commit updates all used Deno modules to their latest version.
Since some of the used modules / functions were deprecated we had to adjust our encrypt / descrypt functions and the generation of the source and item ids, where we have to use a new md5 function.
=> [core] Update Deno Modules

app/lib/widgets/signup/signup.dart
This commit improves our password policy, so that every user which signs up must have a password with a minimum length of 8 characters, one upper and lower case letter and one number.
=> [core] Forbid Weak Passwords

app/lib/widgets/item/details/item_details_reddit.dart
The Reddit source supports YouTube videos now. This means if a Reddit post contains a link to a YouTube video, we render the video in the item details, so that a user can directly watch the video.
=> [reddit] Add Support for YouTube Videos

supabase/functions/_cmd/scheduler/scheduler.ts
Reddit and Nitter are heavlily rate limited from time to time, to not effect our premium users, by these limits, we decided to increase the interval in which the Reddit and Nitter sources are updated for users which are on the free tier.
=> [core] Increase Update Interval for Reddit and Nitter

supabase/functions/image-proxy-v1/index.ts
=> [core] Remove `referer` Check in `image-proxy-v1` Function

.github/workflows/continuous-delivery.yaml, .github/workflows/continuous-integration.yaml, CONTRIBUTING.md, app/android/app/build.gradle, app/android/build.gradle, app/android/settings.gradle, app/ios/Podfile.lock, app/ios/Runner.xcodeproj/project.pbxproj, app/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, app/macos/Podfile.lock, app/macos/Runner.xcodeproj/project.pbxproj, app/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, app/pubspec.lock, app/pubspec.yaml
Upgrade the used version of Flutter to 3.19.1 and all used packages to their latest version.
For the Android Version of the app, we also had to adjust some files, because of the "Deprecated imperative apply of Flutter's Gradle plugins". The steps we had to run for this can be found at https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply
=> [core] Upgrade Flutter Version

.github/workflows/continuous-delivery.yaml, .github/workflows/continuous-integration.yaml, CONTRIBUTING.md
=> [core] Update Flutter Version to 3.19.5

landing/package-lock.json, landing/package.json
=> Revert "Bump the npm group in /landing with 10 updates"

landing/package-lock.json, landing/package.json
=> Fix ESLint Dependency Mismatch

app/lib/widgets/item/details/utils/item_videos.dart, app/lib/widgets/item/preview/utils/item_actions.dart, app/lib/widgets/settings/accounts/utils/settings_accounts_actions.dart, app/lib/widgets/settings/profile/settings_profile_signout.dart
With this commit we are wrapping all action widgets in a `SafeArea` widget, to improve the alignment of the actions.
=> [core] Wrap Actions in `SafeArea` Widget

.github/workflows/continuous-delivery.yaml, .github/workflows/continuous-integration.yaml, app/ios/Podfile.lock, app/ios/Runner/AppDelegate.swift, app/pubspec.lock
=> Update Flutter Version to 3.24.1

.github/workflows/continuous-delivery.yaml, .github/workflows/continuous-integration.yaml, CONTRIBUTING.md
=> Update Flutter Version to 3.29.0

.github/dependabot.yml, .github/release.yaml, .github/workflows/continuous-delivery.yaml
- Use `docker/metadata-action` GitHub Action to determine the tag for
Docker images
- Add `changelog: changed` label to Dependabot PRs
- Adjust `version-resolver` for Release Drafter to use `patch` versions
for PRs with `changelog: changed` label
=> Maintenance: GitHub Actions

.github/workflows/continuous-delivery.yaml, .github/workflows/continuous-integration.yaml, CONTRIBUTING.md
=> Update Flutter Version to 3.29.2

supabase/functions/_cmd/Dockerfile, supabase/functions/_cmd/cmd.ts, supabase/functions/_cmd/scheduler/scheduler.ts, supabase/functions/_cmd/worker/worker.ts, supabase/functions/_shared/feed/utils/getAndParseFeed.ts, supabase/functions/_shared/feed/utils/uploadFile.ts, supabase/functions/add-or-update-source-v1/index.ts, supabase/functions/add-source-v1/index.ts, supabase/functions/delete-user-v1/index.ts, supabase/functions/generate-magic-link-v1/index.ts, supabase/functions/import_map.json, supabase/functions/profile-v1/index.ts, supabase/functions/profile-v2/index.ts, supabase/functions/revenuecat-webhooks-v1/index.ts, supabase/functions/stripe-create-billing-portal-link-v1/index.ts, supabase/functions/stripe-create-checkout-session-v1/index.ts, supabase/functions/stripe-webhooks-v1/index.ts
Update Deno Version in the Docker image to version 1.45.2 and update the
`@supabase/supabase-js` dependency specified in the `import_map.json`
file.
**NOTES:**
- The current recommended approach for managing dependencies is using a
`deno.json` file, which is currently not working locally and returns
the following error:
```
serving the request with supabase/functions/add-or-update-source-v1
worker boot error: failed to create the graph: Relative import path "@supabase/supabase-js" not prefixed with / or ./ or ../
at file:///Users/ricoberger/Documents/GitHub/feeddeck/feeddeck/supabase/functions/add-or-update-source-v1/index.ts:1:30
worker boot error: failed to create the graph: Relative import path "@supabase/supabase-js" not prefixed with / or ./ or ../
at …
```
=> Update Deno Version to 1.45.2

app/lib/widgets/deck/deck_layout_small.dart, app/lib/widgets/item/details/utils/item_audio_palyer/item_audio_player_init/item_audio_player_init.dart, app/lib/widgets/item/details/utils/item_piped/item_piped_video.dart, app/lib/widgets/item/details/utils/item_piped/item_piped_video_web.dart, app/lib/widgets/item/details/utils/item_youtube/item_youtube_video.dart, app/lib/widgets/item/details/utils/item_youtube/item_youtube_video_web.dart, app/pubspec.lock, app/pubspec.yaml
- Change `surfaceVariant` to `surfaceContainerHighest`
- Remove `library` statement
- Migrate from `dart:html` to `package:web/web.dart`
=> Fix Flutter Deprecations

app/lib/widgets/item/details/utils/item_videos.dart, app/lib/widgets/item/details/utils/item_youtube/item_youtube_video_native.dart
Until now we only checkeed if we could fetch a video which contains the
video and audio of a YouTube video. Since this is not always the case we
are now also returning the videos which do not contains the audio and
fetching the corresponding audio file seperatly.
=> [youtube] Fix Video Playback

supabase/hosting/README.md
git and find parameters changed
See: https://github.com/orgs/feeddeck/discussions/217#discussioncomment-12945424
=> Update README.md - git and find parameters changed 

.github/workflows/continuous-integration.yaml, supabase/functions/_e2e/e2e_test.ts, supabase/functions/_shared/models/item.ts, supabase/functions/deno.json
=> Add E2E Test

.github/dependabot.yml, supabase/email-templates/.gitignore, supabase/email-templates/package-lock.json, supabase/email-templates/package.json, supabase/email-templates/tsconfig.json
Update React Email to the latest version and add Dependabot
configuration to keep it up-to-date.
=> Update React Email
