supabase/functions/_shared/feed/rss.ts

If a RSS feed entry did not contain a "published" field, we skipped the entry and didn't added it to the database. Now it is also possible to use feeds without a "published" field. If a feed entry does not contain the field it must contain a "updated" field, which we then use for the "publishedAt" field in the database. If a feed entry doesn't contain one of the two fields the entry is still skipped.

[rss] Allow RSS Feeds without "published" Field

---

app/lib/widgets/source/add/add_source_nitter.dart
supabase/functions/_shared/feed/nitter.ts

It is now possible to use a custom Nitter instances. This means a user must not rely on our Nitter instance and can instead use his own instance. To use a custom Nitter instance a user must provide the full RSS feed url for the instance.

[nitter] Allow Usage of Custom Nitter Instances

---

supabase/functions/_shared/feed/youtube.ts

In the "isYoutubeUrl" function we are checking if the provided url is related to YouTube. For that we checked if the url starts with "https://www.youtube.com/" or "https://m.youtube.com/", but we also have to check if the url starts with "https://youtube.com/" which is used when a users shares a link to a channel via the YouTube app.
In this commit we add the missing "https://youtube.com/" option to the "isYoutubeUrl" function.

[youtube] Add Missing URL in isYoutubeUrl Function

---

supabase/functions/_shared/feed/googlenews.ts
supabase/functions/_shared/feed/mastodon.ts
supabase/functions/_shared/feed/medium.ts
supabase/functions/_shared/feed/nitter.ts
supabase/functions/_shared/feed/podcast.ts
supabase/functions/_shared/feed/reddit.ts
supabase/functions/_shared/feed/rss.ts
supabase/functions/_shared/feed/stackoverflow.ts
supabase/functions/_shared/feed/tumblr.ts
supabase/functions/_shared/feed/youtube.ts

For the item ingestion logic we are now also looking at the published date for all entries in a RSS feed. If the published date is older then the last update date of a source the item will be skipped. This way we should reduce the number of duplicated items, where an entry was updated in the RSS feed, so that it had a new id and was written again to the database and not only updated.

[core] Use Published Date for Item Ingestion

---

app/lib/main.dart

When we used the AppBar widget we did not specify the "centerTitle" property, so that the title was aligned within the default of the platform. This means on iOS and macOS the title was centered, but on Android, Windows and Linux the title was aligned on the left side.
This wasn't intended and we want to have the same style on all Platforms, so that the title is now centered on all Platforms like it was already done on iOS and macOS.

[core] Fix Title Alignment

---

.github/workflows/continuous-delivery.yaml
CONTRIBUTING.md
app/lib/repositories/profile_repository.dart
app/lib/widgets/settings/accounts/settings_accounts_github.dart
supabase/functions/profile-v1/index.ts
supabase/functions/profile-v2/github.ts
supabase/functions/profile-v2/index.ts

This commit introduces a new "profile-v2" edge function and deprecates the "profile-v1" edge function. We decided to provide a new edge function for all profile related operation to improve the handling of the different operation the edge function is responsible for.
The main differences to the "profile-v1" functions are:
- Pass the operation id within the request url instead of the body of the request.
- Move the operations for accounts (e.g. GitHub) to seperate files, to improve the readability of the function.
- Do not require the "sourceType" anymore, instead we are using the operation id and request method to determine the operation which should be executed
- The request body is now only used for the data of the corresponding account and not for any other information like the …

[core] Rework Profile Edge Function

---

app/lib/repositories/settings_repository.dart

Fix the used Google Client ID required for the Android login. The Google Client ID must also be changed in all the Supabase projects.

[core] Fix Google Client ID

---

app/lib/widgets/settings/settings_info.dart
landing/app/terms-and-conditions/page.tsx

This commit adds links to the privacy policy and terms & conditions to the distributed apps as it is required for the in-app purchase submission in the Apple App Store.
This commit also updates the terms & conditions to include a specify section when FeedDeck is used via the Apple App Store, Google Play Store or the Windows Store.

[core] Add Privacy Policy and Terms & Conditions

---

app/lib/widgets/deck/deck_layout_large.dart

This commit fixes the border radius for the drawer used in the large deck layout. Until now the drawer used the border radius on all edges. This is now fixed to only use the border radius on the right side of the drawer. This is more aligned how the border radius is used in the side sheet for the item details, where we also only use it on the left side.

[core] Fix Border Radius for Drawer

---

app/lib/repositories/items_repository.dart

This commit fixes the status of an ItemsRepository when the repository
is initalized from the ItemsRepositoryStore instead of the "_getItems"
function.
After the repository was initialized from the ItemsRepositoryStore we
always set the status of the repository to "loaded", also when we had
less then 50 items. Because of that we also always displayed the "Load
More" button. This is now fixed by adding the status of the repository
to the ItemsRepositoryStore, so that the "Load More" button is only
shown when there are more items to load.

[core] Fix ItemsRepository Status

---

app/lib/repositories/items_repository.dart
app/lib/widgets/column/header/column_layout_header.dart

We always loaded 51 items per fetch instead of 50 items, because we used a range of 0 to 50 which includes the item at position 0 and at position
50. This is now fixed by adjusting the range to 0 to 49, so that exactly 50 items are loaded per fetch request.
This commit also improves the number of loaded items shown in the column header. If the status of the ItemsRepository is "loaded" we add a small "+" symbol behind the number to indicat that there are more items, which could be loaded. If the last page was already fetched (status == "loadedLast") then the "+" symbol isn't shown.

[core] Fix Number of Loaded Items per Fetch

---

app/lib/repositories/items_repository.dart
app/lib/widgets/settings/decks/settings_decks_select.dart
app/lib/widgets/settings/profile/settings_profile_signout.dart

The cached items in the "ItemsRepositoryStore" are now cleared when a user selects an active deck in the settings and when a user signes out of the app.
This is done to force a reload of the items in a column, when a user switches between decks. For me this works better because, when I switch between decks I manually trigger a reload for all columns, which is now not necessary anymore.

[core] Clear Cached Items

---

app/ios/Podfile.lock
app/lib/main.dart
app/lib/widgets/item/details/item_details_mastodon.dart
app/lib/widgets/item/details/utils/item_videos.dart
app/lib/widgets/item/preview/item_preview_mastodon.dart
app/linux/flutter/generated_plugin_registrant.cc
app/linux/flutter/generated_plugins.cmake
app/macos/Flutter/GeneratedPluginRegistrant.swift
app/macos/Podfile.lock
app/pubspec.lock
app/pubspec.yaml
app/windows/flutter/generated_plugin_registrant.cc
app/windows/flutter/generated_plugins.cmake
supabase/functions/_shared/feed/mastodon.ts

It is now possible to play videos from toots within FeedDeck. For that we are using the "madia_kit" package, which is already used for the Podcast player on Windows and Linux.
The videos from a toot are saved within the "options.videos" field of an item next to the "options.media" field. In the "ItemDetailsMastodon" widget we are then checking if this field is present and contains a list of video urls. These urls can then be played via the "ItemVideos" widget.

[mastodon] Add Support for Videos

---

app/lib/widgets/item/details/item_details_rss.dart
app/lib/widgets/item/details/utils/item_description.dart
app/lib/widgets/item/details/utils/item_subtitle.dart
app/lib/widgets/item/preview/item_preview_rss.dart
app/lib/widgets/item/preview/utils/item_description.dart
app/pubspec.lock
app/pubspec.yaml
supabase/functions/_shared/feed/rss.ts

The items of an RSS feed are now rendered better, to achieve this we did the following changes:
- Remove leading and trailing whitespaces from the item description which should be rendered.
- Check if the media file of an item is an SVG image. If this is the case we will not add it to the "media" field in the database, because currently the CachedNetworkImage widget can not render SVGs. If we want to render them, we run into serious performance issue so we skip them completly.
- Always assume that the content of an RSS feed contains HTML and render them as plain text in the preview and as markdown in the details. Since we also render images from the description now, we check if the "item.media" image should be rendered. If the description contains an image we do not render our own image. …

[rss] Improve Rendering of Items

---

app/lib/main.dart
app/lib/repositories/layout_repository.dart
app/lib/widgets/deck/deck_layout_large.dart
app/lib/widgets/deck/deck_layout_small.dart
app/lib/widgets/settings/decks/settings_decks_select.dart

This commit improves the handling of tabs in the samll deck layout. We are now saving the selected tabs index in the newly added "LayoutRepository" so that we can reuse the selected tab when a user switches between the small and large layout. We can now also set the tab which should be initially selected in the large layout when a user selects a column in the navigation rail. Last but not least we can also reset the initial tab index when a user selects a new deck in the settings, so that we always display the first column instead of the column with the same index as it was selected in the previous deck.

[core] Improve Tabs Handling in Small Deck Layout

---

supabase/functions/_shared/feed/github.ts
supabase/functions/_shared/feed/x.ts

If a notification was related to a pull request the link we added to the item didn't work. This should now be fixed, so that when a user clicks on the item he is redirected to the correct pull request which is associated with the item.
This commit also removes an unnecessary "console.log" statement.

[github] Fix Notification Links for PRs

---

app/lib/widgets/item/details/item_details_youtube.dart
app/lib/widgets/item/details/utils/item_videos.dart
app/lib/widgets/item/details/utils/item_youtube/item_youtube_video.dart
app/lib/widgets/item/details/utils/item_youtube/item_youtube_video_native.dart
app/lib/widgets/item/details/utils/item_youtube/item_youtube_video_stub.dart
app/lib/widgets/item/details/utils/item_youtube/item_youtube_video_web.dart
app/pubspec.lock
app/pubspec.yaml

It is now pissible to play YouTube videos on the native desktop clients. To achieve this we removed the "youtube_player_iframe" package which was used before to play YouTube video, but which only supported web, iOS and Android as target platforms.
On the web we are now using our own implementation to render an iframe with for the YouTube video.
On all other platforms we are now using the "youtube_explode_dart" package to fetch the video urls for a YouTube video and then we display them within our own video player (the "ItemVideoPlayer" widget which was added in https://github.com/feeddeck/feeddeck/pull/51). We also decided to switch the package for the iOS and Android implementation which already worked before, because we are now able to play YouTube videos in fullscreen and we only have …

[youtube] Add Desktop Support

---

app/lib/widgets/item/details/utils/item_description.dart
app/lib/widgets/item/details/utils/item_media.dart
app/lib/widgets/item/details/utils/item_media_gallery.dart

The size of the modal bottom sheet to display images had always a max width of 640px on large screens. This wasn't intended an the modal bottom sheet should fill the whole screen. This is now fixed, so that when a user clicks on an image in the details view of an item, the whole screen is used to display the image.

[core] Fix Modal Bottom Sheet Size for Images

---

app/lib/widgets/item/details/utils/item_videos.dart

In the modal bottom sheet where a user can select the video quality the dividers between the different qualities were missing. This commit adds the missing divider, so that the modal bottom sheet looks similar to the other modal bottom sheets we are using (e.g. sign out, account settings).

[core] Add Missing Divider to Video Quality Selection

---

app/lib/widgets/item/preview/item_preview_github.dart

The icons for GitHub items were not shown, because we did not set the correct "sourceIconType", which was required for the "ItemSource" widget.

[github] Fix Icons in Item Preview

---

app/lib/widgets/utils/cached_network_image.dart
app/pubspec.lock
app/pubspec.yaml
app/run.sh

This commit adds a custom cache manager "CustomCacheManager" which is used in the "CachedNetworkImage" widget. The custom cache manager is required, so that we can adjust the stale periode of cached images. By default the package used 30 days as stale periode, but for our use case 7 days should be enough and we can reduce the storage used by the app.

[core] Add Custom Cache Manager

---

app/lib/widgets/source/add/add_source_rss.dart
supabase/functions/_shared/feed/rss.ts
supabase/functions/_shared/feed/utils/getFavicon.ts

Users can now provide the URL of a website instead of the url of a RSS feed via the input field for the RSS source.
This is possible because we are now trying to get and parse the RSS feed for the provided url as usual, but if this operation fails, we try to parse the text as html, so that we can check if it contains a "<link type="application/rss+xml" href="RSS_FEED_URL">" tag. If this is the case we are using this value to try to get and parse the RSS feed again. If it fails again we are returning an error as before.

[rss] Allow Users to Provide a Website URL

---

supabase/functions/_shared/feed/medium.ts
supabase/functions/_shared/feed/nitter.ts
supabase/functions/_shared/feed/rss.ts
supabase/functions/_shared/feed/tumblr.ts

In the `getMedia` function for Medium, Nitter, RSS and Tumblr we checked the content and/or description of an RSS feed entry for a media file, but we didn't pass the string to the `unescape` function first, so that we might missed some media files, because our regular expression were not able to find an image.
Now we are using the `unescape` function before using our regular expression to find the image, similar to how we are also applying the `unescape` function before we save the item description.

[core] Fix `getMedia` Function

---

app/lib/models/source.dart
app/lib/widgets/source/add/add_source.dart
app/lib/widgets/source/source_icon.dart

Instead of defining the icons for a source only within the `SourceIcon` widget, the icons are now defined as extension for the `FDSourceType` enum. The background and foreground colors are also defined within the enum now. This allows us to access the icon of a source outside of the `SourceIcon` widget and we only have to touch the `source.dart` file when adding a new source type.

[core] Improve Icon Handling

---

app/lib/widgets/item/details/utils/item_subtitle.dart

This commit improves the displayed subtitle in the details view of an item. For that we have adjusted the `ItemSubtitle` widget to diplay next to the source title, author and publishing time an corresponding icon. We also increased the space between the items and we are using a `|` instead of a `/` as seperator.

[core] Improve Subtitle in Details View

---

supabase/functions/_shared/feed/reddit.ts

When a Reddit post contained an image it was always rendered as table, where the image was displayed in the left column and the author in the right column. This looked very ugly in the app, so that we are now removing all tables from the description of an Reddit post, so that the image is rendered as large as possible and the author is displayed below the image.

[reddit] Remove Tables from Description

---

supabase/functions/_shared/feed/medium.ts

When using Medium as a source it is possible that the a lot of items might be spam when following a tag. To reduce the spam, we filter these items based on a word list and an calculated score. The score is calculated by the number of words which are included in the title from our word list.

[medium] Remove Spam

---

app/android/app/build.gradle

The change introduced in #71 so that we can run the Android build in a GitHub action, broke the `flutter build appbundle` command to build the Android version for the Google Play store. This commit should fix this, so that we can build the Android version in a GitHub Action and for Google Play.

[core] Fix `build.gradle` File for Android Release

---

app/lib/main.dart
app/lib/widgets/item/details/utils/item_audio_palyer/item_audio_player.dart

On Windows and Linux it could happen that the audio playback for a podcast wasn't stopped when the item details view for a podcast item was closed.
This commit "fixes" the problem, by pausing the audio player, before the widget is disposed.
This commit also fixes the condition when the background audio services should be initialized in the `main.dart` file. Instead of the macOS check, we checked for iOS twice.

[podcast] Stop Audio Playback on Windows and Linux

---

app/lib/widgets/item/preview/utils/item_actions.dart

Until now it was only possible to show the actions for an item by pressing longer on the item. Now a user can also right click on the item to display the actions which feels a bit more natural on desktop devices.

[core] Add Right Click Support for Item Actions

---

app/lib/widgets/item/preview/utils/item_description.dart

This commit removes all blank lines in the item preview description, so that we do not render a blank line as the last line. This was done to improve the style of the item previews, which looked ugly when the last line was a blank line.

[core] Remove Blank in Item Preview Description

---

app/lib/widgets/deck/deck_layout_small.dart

The index was not reset in the `DeckLayoutSmall` widget, when the user selected a new deck in the settings widget. This was caused because the `DefaultTabController` was not rebuild after a new deck was selected, so that the `initialIndex` value was not used.
This is now fixed by adding a `key` to the `DefaultTabController`, which corresponds to the selected deck. This means if the user selects a new deck in the settings the widget will be rebuild and the initial selected tab will be the first one. If a user selects the same deck or switches between the small and large layout the tab will be the formerly selected one.

[core] Fix Index Reset for Tabs in Small Deck Layout

---

app/lib/widgets/item/details/utils/item_description.dart
app/lib/widgets/item/preview/utils/item_description.dart

This commit fixes the conversion of HTML to plain text in the description for an item. Until now it could happen, that the there was no whitespace between some words after the conversion. This is now fixed so that there is always a whitespace between words in the plain text.

[core] Fix Converting of HTML to Plain Text in Description

---

supabase/functions/_shared/feed/rss.ts

Until now we only checked if a website contained a RSS feed which can be used for FeedDeck. Now we are also checking if the website contains a Atom or RDF feed when no RSS feed was found.
For this we are checking `link` tag with the `type="application/atom+xml"` attribute or a link tag with the `type="application/rdf+xml"` attribute.

[rss] Parse Atom and RDF Feeds from Websites

---

app/lib/widgets/item/details/item_details_rss.dart
app/lib/widgets/item/details/utils/item_videos.dart
supabase/functions/_shared/feed/rss.ts
supabase/functions/_shared/feed/rss_test.ts

If an RSS feed contains a video within the `attachments` field, the video will now be added to the `options` field of the item. In the Flutter code we then check if the video field is present in the options and show the video instead of an image in the details view of the item.

[rss] Show Videos from RSS Feeds

---

app/lib/widgets/item/preview/utils/item_actions.dart

On the web the right click on an item to show the actions, doesn't work properly, because the browsers right click menu will be shown first. So it doesn't make sense to show also our right click menu.

[core] Disable Right Click for Item Actions on Web

---

supabase/functions/add-source-v1/index.ts
supabase/functions/delete-user-v1/index.ts
supabase/functions/generate-magic-link-v1/index.ts
supabase/functions/image-proxy-v1/index.ts
supabase/functions/import_map.json
supabase/functions/profile-v1/index.ts
supabase/functions/profile-v2/index.ts
supabase/functions/revenuecat-webhooks-v1/index.ts
supabase/functions/stripe-create-billing-portal-link-v1/index.ts
supabase/functions/stripe-create-checkout-session-v1/index.ts
supabase/functions/stripe-webhooks-v1/index.ts

The used `serve` function from the `std/server` module is deprecated and must be replaced with `Deno.serve`. This was done within this commit.

[core] Replace Deprecated `serve` Function

---

CONTRIBUTING.md
supabase/functions/_cmd/cmd.ts
supabase/functions/_cmd/tools/apple-secret-key.ts
supabase/functions/_cmd/tools/tools.ts
supabase/functions/_shared/feed/nitter_test.ts
supabase/functions/_shared/feed/utils/getAndParseFeed.ts

This commit refactors the existing tools, by moving the tools logic to a new `tools.ts` file, so that the main `cmd.ts` file remains clear.
Besides that we also add a new tool `get-feed` which can be used to run the `getFeed` function from the command line. The function is called with a source and returns the generated source and items, as they are saved in the database by the `add-source-v1` Supabase edge function.

[core] Refactor Tools and add `get-feed` Tool

---

.github/workflows/continuous-delivery.yaml
CONTRIBUTING.md
app/ios/Podfile.lock
app/lib/repositories/items_repository.dart
app/lib/utils/desktop_login_manager.dart
app/lib/utils/sign_in_with_apple.dart
app/lib/widgets/signin/signin.dart
app/lib/widgets/utils/cached_network_image.dart
app/linux/flutter/generated_plugin_registrant.cc
app/linux/flutter/generated_plugins.cmake
app/macos/Podfile.lock
app/pubspec.lock
app/pubspec.yaml

Update the used Flutter version to 3.16.5 and the used packages to their latest version.
The Supabase package contained some breaking changes:
- `functionUrl` is not exported anymore, so that it must be generated by ourselfs
- `Provider` was renamed to `OAuthProvider`
- The `signInWithApple` method was removed and is now implemented by us via the `sign_in_with_apple` package.
We also renamed the `DesktopLoginManager` to `DesktopSignInManager` to use the same naming as in other places of the app, where we are always using sign in and not login.

Update Flutter to Version 3.16.5

---

app/web/_headers

This commit adds the `X-Content-Type-Options`, `X-Frame-Options` and `Referrer-Policy` headers to the web deployment of FeedDeck via the `_headers` file.
See https://developers.cloudflare.com/pages/configuration/headers/

[core] Add Additional Headers for Web Deployment

---

app/lib/widgets/settings/accounts/settings_accounts_github.dart
app/lib/widgets/settings/premium/settings_premium_inapp.dart
app/lib/widgets/settings/premium/settings_premium_stripe.dart
app/lib/widgets/settings/profile/settings_profile_customer_portal.dart

Several widgets which where rendered within a modal bottom sheet didn't used a `SafeArea` widget in the body of the `Scaffold` widget, so that the action buttons on the bottom of the widget where not rendered in the correct position.

[core] Add Missing `SafeArea` Widget

---

app/lib/widgets/item/details/item_details.dart
app/lib/widgets/item/preview/utils/item_actions.dart

This commit adds a new action to the menu shown when a user clicks longer on the item in a column. The new "Open Link" action allows a user to directly open the link of the item, so that the details modal must not be opened anymore to open the link.

[core] Add Open Link Action

---

supabase/functions/_shared/feed/rss.ts
supabase/functions/_shared/feed/rss_test.ts

We do not remove HTML tags from the description of a RSS feed item anymore, because:
- This didn't worked for all feeds, because we first removed the tags and then unescape the data, which didn't make sense
- We render the HTML to Makrdown in the frontend so that the description can contain HTML tags and is still properly rendered and in some case better rendered then before

[rss] Do Not Remove HTML Tags

---

.github/workflows/continuous-delivery.yaml

Update the used GitHub Action runners to `macos-14`, see https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
**Edit:** It looks like this improves the runtime for the macOS and iOS Workflow from round about 6m30s to 4m.

[core] Update macOS GitHub Action Runners

---

.github/workflows/continuous-delivery.yaml

Until now we had to manually build the app for Linux arm64 when we created a new release. Now we are using ubicloud and the `ubicloud-standard-2-arm` GitHub Action runner to build the app for Linux arm64.

[core] Add Continuous Delivery Workflow for Linux arm64

---

app/lib/widgets/reset_password/reset_password.dart
app/lib/widgets/settings/profile/settings_profile_password.dart
app/lib/widgets/signin_with_feeddeck/signin_with_feeddeck.dart
app/lib/widgets/signup/signup.dart

This commit fixes the password validations. In #130 we introduced some stronger password policies to forbid weak passwords, but forgot to change it in all places. Now the same rules are also applying when a user changes his password or resets his password.
During the sign in we do not use the same rules, to not block users which have already signed up, with a password which doesn't match the rules.

[core] Fix Password Validations

---

app/lib/widgets/item/details/item_details_mastodon.dart

The Mastodon source supports YouTube Videos now. This means that if a Mastodon post contains a link to a YouTube video as user can now directly watch the video within the app.
If the post contains a video we render the YouTube video and the description instead of the description, images and videos.

[mastodon] Add Support for YouTube Videos

---

app/lib/widgets/item/details/item_details_nitter.dart
app/lib/widgets/item/details/utils/item_piped/item_piped_video.dart
app/lib/widgets/item/details/utils/item_piped/item_piped_video_native.dart
app/lib/widgets/item/details/utils/item_piped/item_piped_video_stub.dart
app/lib/widgets/item/details/utils/item_piped/item_piped_video_web.dart
app/lib/widgets/item/details/utils/item_videos.dart
app/lib/widgets/item/details/utils/item_youtube/item_youtube_video_native.dart
app/pubspec.lock
app/pubspec.yaml

The Nitter source now supports playing Piped Videos directly within the app. For this we are checking if the Nitter post contains a piped.video url and if this is the case we are using the newly added `ItemPipedVideo` widget to render the video player, to allow users to directly play the video within the app.
To support Piped videos we had to create a new `ItemPipedVideo` widget, which is very similar to the `ItemYoutubeVideo` widget. This means on the web version of FeedDeck we show the Video via an iframe and on the other platforms via our `ItemVideoPlayer` widget. The main difference between Piped and YouTube widget is the different client we use to fetch the video urls. Besides the Piped API returns two different stream one for the video and one for the audio, so that we had to add an …

[nitter] Add Support for Piped Videos

---

supabase/functions/_shared/feed/rss.ts

The images of an RSS feed can now also start with `http://`, which is necessary for some feeds.

[rss] Fix Image Parsing

---

app/lib/widgets/item/details/item_details_lemmy.dart
supabase/functions/_shared/feed/lemmy.ts

If a Lemmy post contains a Piped video it can now by played directly in the app, similar to how it is handled for Nitter posts.

[lemmy] Add Support for Piped Videos

---

app/lib/widgets/item/details/item_details_reddit.dart

If a Reddit post contains a Piped video it can now be played directly within the app, similar to how it is handled in Nitter posts.

[reddit] Add Support for Piped Videos

---

app/lib/widgets/item/details/item_details_mastodon.dart

If a Mastodon post contains a Piped video it can now be played directly within the app, similar to how it is handled for Nitter posts.

[mastodon] Add Support for Piped Videos

---

supabase/functions/_shared/feed/feed.ts
supabase/functions/_shared/feed/fourchan.ts
supabase/functions/_shared/feed/fourchan_test.ts

A 4chan source can now also be added via the RSS source type in the Flutter app. If a user provides the RSS feed of an 4chan board, we check if the url is related to 4chan and if this is the case, we use the 4chan
instead of the RSS source type, similar to how it is handled for other
sources like Medium, Reddit, etc.

[4chan] Improve Options Parsing

---

app/pubspec.lock
app/pubspec.yaml

Use the newest upstream version of the `just_audio_media_kit` package, which removes the hard dependencies on the `media_kit_libs_linux` and `media_kit_libs_windows_audio` packages, so that it shouldn't conflict anymore with the usage of the `media_kit_libs_video` package.

[core] Use Upstream `just_audio_media_kit` Version

---

app/lib/widgets/item/details/utils/item_description.dart
app/lib/widgets/item/preview/utils/item_description.dart

This commit fixes the style of blockquotes when we render the item description as Markdown. Until now blockquotes had a weird blue background, so that the text wasn't readable.
Now we are using the surface color as background and we add a border on the left site with the primary color.
We would also like to use italic as font family, but there is currently a bug, so that the defined blockquote style is not applied. See https://github.com/flutter/flutter/issues/81720

[core] Fix Blockquote Style

---

supabase/migrations/20240312204702_add_indexes.sql

Until now it could happen that the items for a column could not be retrieved from the database, because of the set query timeout. In this case we received the following error:
```
PostgrestException(message: canceling statement due to statement timeout, code: 57014, details: Internal Server Error, hint: null)
```
To fix this issue we added an `items_columnId_idx` index, so that the items for a column are retrieved fast.
We also added some other useful indexes to improve the overall performance of our queries.
Last but not least we also added an index to the `userId` columns as it is recommended by Supabase to improve the performance of our RLS policies.

[core] Add Indexes to Improve Query Performance

---

.github/workflows/continuous-delivery.yaml

Upload the raw build of the app in the Windows CI/CD pipeline, so that we can test the production build during a new release.
We also had to adjust the Windows runner to `windows-2019`, because the build on `windows-latest` and `windows-2022` can not be startet after downloading it.

[core] Upload Raw Build in Windows CI/CD Pipeline

---

.github/workflows/continuous-delivery.yaml
app/lib/main.dart
app/lib/widgets/item/details/utils/item_audio_palyer/item_audio_player_init/item_audio_player_init.dart
app/lib/widgets/item/details/utils/item_audio_palyer/item_audio_player_init/item_audio_player_init_native.dart
app/lib/widgets/item/details/utils/item_audio_palyer/item_audio_player_init/item_audio_player_init_stub.dart
app/lib/widgets/item/details/utils/item_audio_palyer/item_audio_player_init/item_audio_player_init_web.dart

Fix web build be initializing `JustAudioMediaKit` only on Linux and Windows where it is really used. The corresponding issue for the broken web build can be found here https://github.com/Pato05/just_audio_media_kit/issues/15.
To test the web build on every PR to avoid such issues, the CI/CD pipeline for the web build is now also run on every PR. On PRs we skip the upload to Cloudflare for the web build.

[core] Fix Web Build

---

supabase/functions/_shared/feed/rss.ts
supabase/functions/_shared/feed/rss_test.ts

Until now, we always checked the `description` field of an item first to
get our description value. If the `description` field is present we
directly used it and never checked the `content` field.
Now we are checking the `content` field first and afterwards the
`description` field. This way by default the `content` field is used as
our description. This should be more common to get the full article text
when both fields are present in an RSS feed.
When both fields are present and the `description` field is longer then
the `content` field, we will still prefer the `description` field.
Closes #226

Prefer `content` over `description` for Item Description

---

app/lib/repositories/app_repository.dart
app/lib/widgets/column/header/column_layout_header_settings_sources.dart
app/lib/widgets/source/source_list_item.dart
supabase/migrations/20250419122600_add_postion_field_to_sources.sql

It is now possible to re-order sources in a column by dragging them into
a new position. To achieve this a new `position` field was added to the
`sources` column, which contains the index of the source in the column.
We also added a new `updateSourcePositions` function, which is used to
sort the sources locally and update `position` field in the database
afterwards. The dragging is handled via a `ReorderableListView` widget.
Last but not least the selection of sources from the database was
changed, so order them by the `position` column and if the column is
`null` by the `createdAt` data as it was before.

Allow Re-Ordering of Sources in a Column

---

app/lib/widgets/deck/deck_layout_small.dart

It is now possible to switch the column in a deck by swiping to the left
/ right.
Closes #228

Allow Swiping Gestures to Switch Column

---

app/android/.gitignore
app/android/app/build.gradle
app/ios/Podfile
app/ios/Podfile.lock
app/ios/Runner/Info.plist
app/lib/models/column.dart
app/lib/models/source.dart
app/lib/models/sources/github.dart
app/lib/models/sources/googlenews.dart
app/lib/models/sources/stackoverflow.dart
app/lib/repositories/app_repository.dart
app/lib/widgets/item/details/utils/item_piped/item_piped_video_web.dart
app/lib/widgets/item/details/utils/item_youtube/item_youtube_video_web.dart
app/lib/widgets/settings/app_settings/app_settings.dart
app/lib/widgets/settings/app_settings/app_settings_export.dart
app/lib/widgets/settings/app_settings/app_settings_import.dart
app/lib/widgets/settings/settings.dart
app/macos/Flutter/GeneratedPluginRegistrant.swift
app/macos/Podfile.lock
app/macos/Runner/DebugProfile.entitlements
app/macos/Runner/Release.entitlements
app/macos/Runner/RunnerDebug.entitlements
app/pubspec.lock
app/pubspec.yaml
app/run.sh

It is now possible import and export decks. Decks can be imported from
OPML files. For each import a new deck is created. If the OPML file
contains nested `outline` tags, we will create one column for each
parent `outline` tag. Otherwise we will create a column named `Unknown`
and all sources to this column. When a deck is exported we will create
one `outline` tag for each column with it's sources as siblings.
Closes #229

Allow Importing / Exporting of Decks

---

supabase/functions/_e2e/e2e_test.ts
supabase/migrations/20250502162957_adjust_database_functions.sql

- Set `search_path` for all database functions, as this is recommended
by the Supabase security advisor
- Fix `items_delete` functions: The function was never working, which
caused that we saved to many items for a source, which slowed down our
performance
- Revoke execution rights for users for the `sources_delete_files` and
`items_delete` functions
- Add E2E test, to check if users can call the database functions

Adjust Database Functions

---

app/lib/widgets/source/source_list_item.dart

Remove the drag handle icon from the sources. The icon was used together
with the `ReorderableDragStartListener` widget to sort the sources. This
can now be done without the icon, because we wrap the source card widget
within the `ReorderableDragStartListener` widget.

Remove Drag Handles from Sources

---

app/lib/utils/openurl.dart

Instead of using an external browser on Android, we are now using the
In-App-Browser to open all urls. For all other platforms we keep the
current behaviour and just set the launch mode explicitly, for the case
the the default is changed in the used package.
Closes #261

Improve `openUrl` Function
